### ISSUE TITLE
Only 15 out of 17 SDGs labeled? 

### ISSUE THREAD

**Issue by jonas-nothnagel** [osdg-ai/osdg-data#3]
Hi everyone!

Glad to see this work moving forward! Is there a reason why the dataset contains only labels for the first 15 SDGs?

**Comment by filippo82** [comment]
I've checked all the three versions of the dataset and there indeed no examples for SDG 16 and 17.

Maybe @mykolaskrynnyk has an answer?

**Comment by jonas-nothnagel** [comment]
just fyi @filippo82 the osdg dataset was used in this [project](https://edarxiv.org/ws3tk) and the authors state the following: 

"The dataset only includes SDGs between 1-15 because SDGs 16 and 17 are overarching goals that might pop up in almost all kinds of texts."

Hence it is safe to assume that SDG 16 + 17 were not part of the annotation exercise. Closing the issue.

**Comment by filippo82** [comment]
Thanks for the info 👍🏻
